### ISSUE TITLE
Upgrade to latest framework spec

### ISSUE THREAD

**Issue by robertjd** [stormpath/express-stormpath#298]
This is the root issue for the milestone.  Create more issues to track work and issue PR's against the "framework-spec-upgrade" branch.

Latest spec can be found here:

https://github.com/stormpath/stormpath-framework-spec

High level todos (list may not be complete yet):

* [x] Upgrade [JSON error responses](https://github.com/stormpath/stormpath-framework-spec/blob/master/error-handling.md#error-handling) (#325)
* [x] Implement ["produces"](https://github.com/stormpath/stormpath-framework-spec/blob/master/single-page-apps.md#configuration)  options
 * [x] Implement produces option for `/login` (#308)
 * [x] Implement produces option for `/register` (#309)
 * [x] Implement produces option for `/verify` (#327)
 * [x] Implement produces option for `/forgot` (#326)
 * [x] Implement produces option for `/change` (#328)
 * [x] Implement produces option for `/logout` (#341)
* [x] Implement ["SPA"](https://github.com/stormpath/stormpath-framework-spec/blob/master/single-page-apps.md#configuration) options (#319)
* [x] Implement JSON view models
  * [x] Implement [view models](https://github.com/stormpath/stormpath-framework-spec/blob/master/login.md#login-view-model) for GET on `/login` (#306)
  * [x] Implement [view models](https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md#registration-view-model) for GET on `/register` (#307)
* [ ] Upgrade view models for latest registration configuration model, if the changes can be done in a non-breaking way
* [x] Implement [GitHub](https://github.com/stormpath/stormpath-framework-spec/blob/master/social.md#feature-description) social provider support (#312)
* [x] Add support for [`stormpath.web.social`](https://github.com/stormpath/stormpath-framework-spec/blob/master/social.md#implementing-page-based-workflows) config options (#316)
* [x] Use [local token validation](http://docs.stormpath.com/nodejs/express/latest/authentication.html#token-validation-strategy) by default (#315)

**Comment by timothyej** [comment]
FYI: I just created the `framework-spec-upgrade` branch:

https://github.com/stormpath/express-stormpath/tree/framework-spec-upgrade

**Comment by edjiang** [comment]
@robertjd Just ran my test suite against the current version of `framework-spec-upgrade`; looks pretty good, only thing left is /me should be returning things wrapped in an account object =]

**Comment by robertjd** [comment]
Done!! Huge props to @timothyej and @typerandom
